[GECO-62] use september-util to send exception over kafka
diging/giles-eco-nepomuk pull request #18
Opened 2017-04-20 22:35 UTC by snilapwa

2017-04-21 17:02 UTC, jdamerow requested changes

2017-04-21 17:02 UTC, jdamerow commented on nepomuk/src/main/java/edu/asu/diging/gilesecosystem/nepomuk/core/config/NepomukExceptionConfig.java
> +public class NepomukExceptionConfig {
lets just call that NepomukConfig since we'll probably add other beans here as well in the future that have nothing to do with exceptions.

2017-04-21 17:02 UTC, jdamerow commented on nepomuk/src/main/java/edu/asu/diging/gilesecosystem/nepomuk/core/kafka/impl/StorageRequestReceiver.java
> +    private NepomukExceptionConfig exceptionConfig;
don't autowire the configuration. autowire the bean you actually need.

2017-04-21 17:02 UTC, jdamerow commented on nepomuk/src/main/java/edu/asu/diging/gilesecosystem/nepomuk/rest/FilesController.java
> -            systemMessageHandler.handleError("Could not write to output stream.", e);
the message handler logs the exception, so it shouldn't be logged here as well

2017-04-21 17:02 UTC, jdamerow commented on nepomuk/src/main/java/edu/asu/diging/gilesecosystem/nepomuk/rest/FilesController.java
> -            systemMessageHandler.handleError("Could not write to output stream.", e);
same is true everywhere

2017-04-21 23:34 UTC, jdamerow requested changes

2017-04-21 23:34 UTC, jdamerow commented on nepomuk/src/main/java/edu/asu/diging/gilesecosystem/nepomuk/core/kafka/impl/StorageRequestReceiver.java
> +    private SystemMessageHandler messageHandler;
does the message handler not have an interface?

2017-04-26 18:19 UTC, jdamerow requested changes

2017-04-26 18:19 UTC, jdamerow commented on nepomuk/src/main/java/edu/asu/diging/gilesecosystem/nepomuk/core/config/NepomukConfig.java
> +    public SystemMessageHandler getMessageHandler() {
should return interface

2017-04-26 18:19 UTC, jdamerow commented
almost

2017-04-26 18:50 UTC, snilapwa commented on nepomuk/src/main/java/edu/asu/diging/gilesecosystem/nepomuk/core/config/NepomukConfig.java
> +    public SystemMessageHandler getMessageHandler() {
Done

2017-04-26 21:49 UTC, jdamerow approved these changes

2017-04-26 21:49 UTC, jdamerow commented
ok to test

2017-04-26 21:53 UTC, jdamerow commented
please reopen when september-util has been merged.

2017-04-29 00:09 UTC, merged