Story/geco 98
diging/giles-eco-nepomuk pull request #26
Opened 2018-04-12 19:08 UTC by abhikrish503501

2018-04-12 20:24 UTC, Mihika0409 approved these changes

2018-04-12 22:40 UTC, jdamerow requested changes

2018-04-12 22:40 UTC, jdamerow commented on nepomuk/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
> +	<context:component-scan base-package="edu.asu.diging.gilesecosystem.nepomuk.web, edu.asu.diging.gilesecosystem.kafka.util, edu.asu.diging.gilesecosystem.util.properties" />
these are already scanned by the root context and don't need to be scanned again.

2018-04-12 22:40 UTC, jdamerow commented on nepomuk/src/main/webapp/WEB-INF/views/admin/manage_listeners.jsp
> +		Kafka listeners have been stopped !
remove blanks before exclamation marks

2018-04-13 20:59 UTC, jdamerow requested changes

2018-04-13 20:59 UTC, jdamerow commented on nepomuk/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
> +	<context:component-scan base-package="edu.asu.diging.gilesecosystem.nepomuk.web,edu.asu.diging.gilesecosystem.kafka.util" />
you want the services in the root context. only scan the controller package here.

2018-04-16 19:47 UTC, jdamerow requested changes

2018-04-16 19:47 UTC, jdamerow commented on nepomuk/src/main/webapp/WEB-INF/spring/root-context.xml
> +	<context:component-scan base-package="edu.asu.diging.gilesecosystem.requests,edu.asu.diging.gilesecosystem.nepomuk.core,edu.asu.diging.gilesecosystem.util,edu.asu.diging.gilesecosystem.kafka.util" /
this should only scan the services, otherwise you end up with two instances of the controllers

2018-04-18 21:17 UTC, merged