Story/geco 1: Nepomuk needs to allow app registration to use its API
diging/giles-eco-nepomuk pull request #5
Opened 2016-12-09 23:43 UTC by snilapwa

2017-01-25 19:51 UTC, jdamerow requested changes

2017-01-25 19:51 UTC, jdamerow commented on nepomuk/src/main/resources/providers.properties
> +mitreidconnect=MITREid Connect Server
These are unnecessary

2017-01-25 19:51 UTC, jdamerow commented on nepomuk/src/main/java/edu/asu/diging/gilesecosystem/nepomuk/core/tokens/impl/TokenService.java
> +    public String generateApiToken(User user) {
I don't think you need this method and the user class.

2017-01-26 17:25 UTC, snilapwa commented on nepomuk/src/main/resources/providers.properties
> +mitreidconnect=MITREid Connect Server
Removed

2017-01-26 17:25 UTC, snilapwa commented on nepomuk/src/main/java/edu/asu/diging/gilesecosystem/nepomuk/core/tokens/impl/TokenService.java
> +    public String generateApiToken(User user) {
Removed extra functions and User class

2017-01-27 19:12 UTC, jdamerow commented
please resolve conflicts

2017-01-27 19:12 UTC, closed without merging